apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oz4q8oji4-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oz4q8oji4-go 
  name: oz4q8oji4-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oz4q8oji4-go 
